# Generated by Django 2.2.6 on 2019-11-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='longtext',
            field=models.TextField(default='', help_text='这个是longtext'),
        ),
    ]
